routes/web.php
<?php

use App\Http\Controllers\ACLController;
use App\Http\Controllers\AgihanController;
use App\Http\Controllers\AuditLogController;
use App\Http\Controllers\CabutanController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\LampiranController;
use App\Http\Controllers\MeetingController;
use App\Http\Controllers\ReplyController;
use App\Http\Controllers\UserController;
use App\Models\Role;
use App\Services\DocumentUploadService;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('dashboard');
    // return view('welcome');
});

Auth::routes([
    'register' => false, // Registration Routes...
    // 'reset' => false, // Password Reset Routes...
    // 'verify' => false, // Email Verification Routes...
]);




Route::middleware(['auth', 'role:' . implode('|', Role::ALL_SYSTEM_ROLES)])->group(function () {
    // Route::prefix('/dokumen/{jenis}')->controller(DocumentController::class)->middleware('role:' . Role::PERANAN_PENTADBIR . '|' . Role::PERANAN_KETUA_JABATAN)->name('documents.')->group(function () {
    Route::prefix('/dokumen/{jenis}')->controller(DocumentController::class)->middleware('role:' . Role::PERANAN_PENTADBIR)->name('documents.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::post('/', 'store')->name('store');
        Route::get('/create', 'create')->name('create');
        Route::prefix('/{document}')->group(function () {
            Route::get('/', 'show')->name('show');
            Route::put('/', 'update')->name('update');
            Route::get('/edit', 'edit')->name('edit');
            Route::delete('/', 'destroy')->name('destroy');
            Route::resource('/lampirans', LampiranController::class, [
                'only'  =>  ['store', 'destroy']
            ]);
            Route::group(['prefix' => '/agihans', 'as' => 'agihans.', 'middleware'  => ['cannot-set-agihan']], function () {
                Route::post('/store', [AgihanController::class, 'store'])->name('store');
                Route::post('/resend', [AgihanController::class, 'resend'])->name('resend');
                Route::post('/reset', [AgihanController::class, 'reset'])->name('reset');
            });
        });
    });

    Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');


    Route::prefix('/mesyuarat/{jenis}')->controller(MeetingController::class)->middleware('role:' . Role::PERANAN_PENTADBIR . '|' . Role::PERANAN_KETUA_JABATAN)->name('meetings.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::post('/', 'store')->name('store');
        Route::get('/create', 'create')->name('create');
        Route::prefix('/{meeting}')->group(function () {
            Route::get('/', 'show')->name('show');
            Route::put('/', 'update')->name('update');
            Route::get('/edit', 'edit')->name('edit');
            Route::delete('/', 'destroy')->name('destroy');
            Route::get('/agihan', 'agihan')->name('agihan');
            Route::resource('/lampirans', LampiranController::class, [
                'only'  =>  ['store', 'destroy']
            ]);
            Route::resource('/cabutans', CabutanController::class, [
                'only'  =>  ['store', 'update', 'destroy']
            ]);
            Route::group(['prefix' => '/agihans', 'as' => 'agihans.'], function () {
                Route::post('/store', [AgihanController::class, 'store'])->name('store');
                Route::post('/resend', [AgihanController::class, 'resend'])->name('resend');
                Route::post('/reset', [AgihanController::class, 'reset'])->name('reset');
            });
        });
    });

    Route::controller(LampiranController::class)->prefix('lampirans')->name('lampirans.')->group(function () {
        Route::get('{lampiran}/download', 'download')->name('download');
    });

    Route::delete("/lampirans/{lampiran}", [LampiranController::class, 'destroy'])->name('lampirans.destroy');

    Route::middleware(['role:' . Role::PERANAN_PENTADBIR . '|' . Role::PERANAN_PENTADBIR_SISTEM])->group(function () {
        Route::resources([
            'departments' => DepartmentController::class,
            'users' => UserController::class,
        ]);
        Route::put('/users/{user}/changepassword', [UserController::class, 'changePassword'])->name('users.change-password');
        Route::prefix('/users/{user}/acls')->middleware('cannot-update-self-role-access')->group(function () {
            Route::put('/', [ACLController::class, 'update'])->name('acls.update');
            Route::get('/edit', [ACLController::class, 'edit'])->name('acls.edit');
            Route::post('/reset', [ACLController::class, 'reset'])->name('acls.reset');
        });
        Route::get('/acls', [ACLController::class, 'index'])->name('acls.index');
    });




    //Azrul Tambah
    Route::middleware(['role:' . Role::PERANAN_KETUA_JABATAN])->group(function () {
        Route::get('/users/{id}', [App\Http\Controllers\UserController::class, 'index'])->name('user.index');
        Route::get('/maklumbalas/index', [App\Http\Controllers\ReplyController::class, 'index'])->name('maklumbalas.index');
        Route::get('/mesyuarat/mesyuarat-jemaah-menteri', [App\Http\Controllers\MeetingController::class, 'index'])->name('mesyuarat.mesyuarat-jemaah-menteri');
        // Route::get('/mesyuarat/mesyuarat-jemaah-menteri/{meeting}', [App\Http\Controllers\MeetingController::class, 'show'])->name('mesyuarat.mesyuarat-jemaah-menteri.show');
        Route::get('/mesyuarat/mesyuarat-utama', [App\Http\Controllers\MeetingController::class, 'index'])->name('mesyuarat.mesyuarat-utama');

        Route::get('/view/docs/{lampiran}', [LampiranController::class, 'download'])->name('view.docs');
        Route::group(['prefix' => 'maklumbalas', 'as' => 'reply.'], function () {
            Route::get('/', [ReplyController::class, 'index'])->name('index')->middleware('can:view-maklum-balas');

            Route::prefix('/{model}/{model_id}/ulasan/{agihan}')->group(function () {
                Route::get('/', [ReplyController::class, 'show'])->name('show');
                Route::post('/', [ReplyController::class, 'store'])->name('store')->middleware('can-update-reply');
            })->middleware(['valid-feedback-url']);
        });

    });





    // Route::get('/dashboard', 'HomeController@index')->name('dashboard');

    Route::group(['prefix'  => '/logaudit', 'as' => 'logaudit.', 'middleware' => 'role:' . Role::PERANAN_PENTADBIR. '|' . Role::PERANAN_PENTADBIR_SISTEM], function () {
        Route::prefix('/pengguna')->name('pengguna.')->group(function () {
            Route::get('/', [AuditLogController::class, 'indexUserLogs'])->name('index');
            Route::get('/{user}/{type?}', [AuditLogController::class, 'showUserLogs'])->name('show');
        });

        Route::prefix('/dokumen')->name('dokumen.')->group(function () {
            Route::get('/{type?}', [AuditLogController::class, 'indexDocumentLogs'])->name('index');
            Route::get('/dokumen/{document}', [AuditLogController::class, 'showDocumentLogs'])->name('document.show');
            Route::get('/mesyuarat/{meeting}', [AuditLogController::class, 'showMeetingLogs'])->name('meeting.show');
        });
    });
});

Route::group(['prefix' => '/test'], function () {
    Route::get('/downloadwithwatermark/{watermarkString}', function () {

        $path = base_path("/tests/TestAssets/lorem-ipsum.pdf");

        $doc = (new DocumentUploadService())->setWatermarkToDoc($path, request()->watermarkString);

        return response()->download($doc, null);
    });
});

app/Models/Meeting.php
<?php

namespace App\Models;

use App\Jobs\TriggerLogs;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Meeting extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'name',
        'tarikh_mesyuarat',
        'is_approved',
        'jenis',
        'tujuan',
        'approved_date',
        'ringkasan',
        'no_rujukan_fail',
        'tarikh_tutup',
    ];

    // ---------------------------------
    // Relationship
    // ---------------------------------
    public function lampirans()
    {
        return $this->morphMany(Lampiran::class, 'lampiranable');
    }

    public function agihans()
    {
        return $this->morphMany(Agihan::class, 'agihanable');
    }

    public function cabutans()
    {
        return $this->hasMany(Cabutan::class);
    }

    // ---------------------------------
    // Accessors & Mutators
    // ---------------------------------

    protected function tarikhMesyuarat(): Attribute
    {
        return Attribute::make(
            get: fn ($value) => Carbon::parse($value)->format('d-m-Y'),
        );
    }

    protected function approvedDate(): Attribute
    {
        return Attribute::make(
            get: fn ($value) => Carbon::parse($value)->format('d-m-Y'),
        );
    }

    protected function getJabatanAgihansAttribute()
    {
        $agihans = $this->agihans()->get();

        $jabatans = [];

        foreach($agihans as $agihan) {
            if (!in_array($agihan->jabatan_penerima, $jabatans)) {
                array_push($jabatans, $agihan->jabatan_penerima);
            }
        }

        return $jabatans;
    }

    public function auditLogs(): MorphMany
    {
        return $this->morphMany(AuditLog::class, 'loggable');
    }

    protected static function booted(): void
    {
        static::created(function (Meeting $meeting) {
            dispatch(new TriggerLogs(auth()->user(), Meeting::class, $meeting->id, 'created'));
        });

        static::updated(function (Meeting $meeting) {
            dispatch(new TriggerLogs(auth()->user(), Meeting::class, $meeting->id, 'updated', $meeting->getChanges()));
        });

        static::deleted(function (Meeting $meeting) {
            dispatch(new TriggerLogs(auth()->user(), Meeting::class, $meeting->id, 'deleted'));
        });
    }
}

app/Http/Controllers/MeetingController.php
<?php

namespace App\Http\Controllers;

use App\Action\CreateAgihan;
use App\Http\Requests\StoreMeetingRequest;
use App\Http\Requests\UpdateMeetingRequest;
use App\Models\Agihan;
use App\Models\Cabutan;
use App\Models\Department;
use App\Models\Meeting;
use App\Models\User;
use Illuminate\Http\Request;

class MeetingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $meetings = Meeting::where('jenis', $request->jenis)
            ->when(request()->carian, function ($q) {
                $q->where(function ($sub) {
                    $sub->where('name', 'LIKE', '%' . request()->carian . '%');
                });
            })
            ->orderBy('name', 'ASC')
            ->paginate(10);

        return view('Meeting.index', [
            'jenis' => $request->jenis,
            'meetings' => $meetings,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        return view('Meeting.create-multistep', [
            'jenis' => $request->jenis,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreMeetingRequest  $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(StoreMeetingRequest $request)
    {

        $meeting = new Meeting();
        $meeting->name = $request['name'];
        $meeting->tarikh_mesyuarat = $request['tarikh_mesyuarat'];
        $meeting->is_approved = $request['is_approved'];
        $meeting->jenis = $request['jenis'];
        $meeting->tujuan = $request['tujuan'];
        $meeting->approved_date = $request['approved_date'];
        $meeting->ringkasan = $request['ringkasan'];
        $meeting->no_rujukan_fail = $request['no_rujukan_fail'];
        $meeting->save();

        session()->flash('status', [
            'type'      => 'success',
            'message'   => 'Maklumat Berjaya Disimpan',
        ]);

        return redirect(route('meetings.index', [
            'jenis'   => request()->jenis,
        ]));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Meeting  $meeting
     *
     * @return \Illuminate\Http\Response
     */
    public function show(Meeting $meeting)
    {
        dd($meeting);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Meeting  $meeting
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($jenis, Meeting $meeting)
    {
        if (!isset(request()->step) || (!in_array(request()->step, [1, 2, 3, 4]))) {
            return redirect()->route('meetings.edit', ['jenis'   => request()->jenis, 'meeting' => $meeting->id, 'step' => 1]);
        }

        if (request('kemaskini_cabutan', null)) {
            $current_cabutan = Cabutan::where('id', request()->kemaskini_cabutan)->where('meeting_id', $meeting->id)->first();

            if (!$current_cabutan) {
                return redirect()->route('meetings.edit', ['jenis'   => request()->jenis, 'meeting' => $meeting->id, 'step' => 4]);
            }
        }

        $lampirans = $meeting->lampirans()->where('jenis', 'mesyuarat')->orderBy('name', 'ASC')->paginate(10, ['*'], 'lampiran_page');
        $cabutans = $meeting->cabutans()->get();

        return view('Meeting.edit-multistep', [
            'meeting'       => $meeting,
            'jenis'         => $meeting->jenis,
            'departments'   => Department::all(),
            'lampirans'     => $lampirans,
            'cabutans'      => $cabutans
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateMeetingRequest  $request
     * @param  \App\Models\Meeting  $meeting
     *
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateMeetingRequest $request, $jenis, Meeting $meeting, CreateAgihan $createAgihan)
    {
        // dd($request->all(), $meeting);

        $user = auth()->user();

        $meeting->name = $request['name'];
        $meeting->tarikh_mesyuarat = $request['tarikh_mesyuarat'];
        $meeting->is_approved = $request['is_approved'];
        $meeting->jenis = $request['jenis'];
        $meeting->tujuan = $request['tujuan'];
        $meeting->approved_date = $request['approved_date'];
        $meeting->ringkasan = $request['ringkasan'];
        $meeting->no_rujukan_fail = $request['no_rujukan_fail'];
        $meeting->tarikh_tutup =  $request['tarikh_tutup'];
        $meeting->save();

        session()->flash('status', [
            'type' => 'success',
            'message' => 'Maklumat berjaya dikemaskini.',
        ]);

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Meeting  $meeting
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($jenis, Meeting $meeting)
    {
        $meeting->delete();

        if ($meeting) {
            request()->session()->flash('status', [
                'type' => 'success',
                'message' => 'Maklumat Berjaya Dihapus',
            ]);
        } else {
            request()->session()->flash('status', [
                'type' => 'danger',
                'message' => 'Maklumat Gagal Dihapus',
            ]);
        }

        return redirect(route('meetings.index', ['jenis'   => request()->jenis]));
    }

    public function agihan($jenis, Meeting  $meeting)
    {
        return view('Meeting.agihan', [
            'meeting' => $meeting->load('agihans'),
            'departments' => Department::all(),
        ]);
    }
}

resources/views/Meeting/agihan.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-header d-flex justify-content-between">
                        <div class="my-auto">Agihan Mesyuarat {{ $meeting->name }}
                        </div>
                        <div>
                            <a class="btn btn-outline-primary" href="{{ route('meetings.edit', ['jenis'   => request()->jenis, $meeting]) }}">Back</a>
                        </div>

                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-{{ session('status.type') }}" role="alert">
                                {{ session('status.message') }}
                            </div>
                        @endif

                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <form action="{{ route('agihans.store') }}" method="POST">
                            @csrf
                            <input type="hidden" name="model_id" value="{{ $meeting->id }}">
                            <input type="hidden" name="jenis" value="meetings">
                            @foreach ($departments as $department)
                                <input type="checkbox" name="departments[]" value="{{ $department->shortcode }}"><label
                                    class="ml-2">{{ $department->name }} ({{ $department->section }}) </label><br />
                            @endforeach

                            <button class="float-end btn btn-primary" type="submit">Agih</button>
                        </form>
                    </div>

                </div>


            </div>
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header d-flex justify-content-between">
                        <div class="my-auto">Agihan Mesyuarat {{ $meeting->name }}
                        </div>
                        <div>
                            <a class="btn btn-outline-primary"
                                href="{{ route('meetings.index', ['jenis'   => request()->jenis, ]) }}">Back</a>
                        </div>

                    </div>

                    <div class="card-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Penerima</th>
                                    <th>Waktu Hantar</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($meeting->agihans as $agihan)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $agihan->penerima }}</td>
                                        <td>{{ $agihan->created_at }}</td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td>Tiada Agihan </td>
                                    </tr>
                                @endforelse
                                <tr>

                                </tr>
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
    </div>
@endsection

resources/views/Meeting/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-footer my-auto clearfix"> Keputusan Mesyuarat
                        @if (request()->jenis == 'mesyuarat-jemaah-menteri')
                            Jemaah Menteri
                        @elseif (request()->jenis == 'mesyuarat-utama')
                            Utama
                        @else
                            '[Tiada Jenis]'
                        @endif

                        {{-- @hasanyrole('Pentadbir') --}}
                        <a class="btn btn-primary float-right"
                        href="{{ route('meetings.create', ['jenis' => request()->jenis]) }}">Cipta
                        baharu</a>
                        {{-- @endhasanyrole --}}
                    </div>


                    {{-- <div class="card-header d-flex justify-content-between">
                        <div class="my-auto">Keputusan Mesyuarat
                            @if (request()->jenis == 'mesyuarat-jemaah-menteri')
                                Jemaah Menteri
                            @elseif (request()->jenis == 'mesyuarat-utama')
                                Utama
                            @else
                                '[Tiada Jenis]'
                            @endif
                        </div>

                        <a class="btn btn-primary float-right"
                            href="{{ route('meetings.create', ['jenis' => request()->jenis]) }}">Cipta
                            {{ ucfirst(request()->jenis) }}
                            baharu</a>
                    </div> --}}

                    <div class="row" style="margin: 16px 16px 0 16px">
                        <x-carian reset-route="{{ route('documents.index', request()->jenis) }}"></x-carian>
                    </div>

                    <div class="card-body table-responsive">
                        <x-success-message-banner></x-success-message-banner>
                        <x-error-message-banner></x-error-message-banner>
                        <table class="table text-center">
                            <thead>
                                <tr>
                                    <th>Bil</th>
                                    <th>Tarikh Minit</th>
                                    <th>Tujuan</th>
                                    <th>No Fail / Tajuk Minit</th>
                                    <th>Tarikh Akhir Maklum Balas</th>
                                    <th>Tindakan</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($meetings as $meeting)
                                    <tr>
                                        <td>{{ $loop->iteration + $meetings->firstItem() - 1 }}</td>
                                        <td>{{ $meeting->tarikh_mesyuarat }}</td>
                                        <td>{{ $meeting->tujuan }}</td>
                                        <td>{{ $meeting->no_rujukan_fail }} / {{ $meeting->name }}</td>
                                        <td>{{ $meeting->tarikh_tutup != null ? $meeting->tarikh_tutup : 'Belum Ditetapkan' }}
                                        </td>
                                        <td>
                                            {{-- <a href="{{ route('meetings.show', ['jenis' => request()->jenis, 'meeting' => $meeting]) }}"
                                                class="btn btn-warning">Lihat</a> --}}
                                            {{-- @hasanyrole('Pentadbir') --}}
                                            <a href="{{ route('meetings.edit', ['jenis' => request()->jenis, 'meeting' => $meeting]) }}"
                                                class="btn btn-warning">Kemaskini</a>
                                            <button type="button" class="btn btn-danger"
                                                onclick="deleteMeeting(event, `Hapus mesyuarat '{{ $meeting->name }}' ?`, 'delete_meeting_form_{{ $meeting->id }}')">
                                                Hapus
                                            </button>
                                            <form id="delete_meeting_form_{{ $meeting->id }}"
                                                action="{{ route('meetings.destroy', ['jenis' => request()->jenis, 'meeting' => $meeting]) }}"
                                                method="POST">
                                                @csrf
                                                @method('DELETE')
                                            </form>
                                                {{-- @endhasanyrole --}}
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="6">Tiada dokumen.</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                        {{ $meetings->withQueryString()->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
<script>
    const deleteMeeting = (event, message, formId) => {
        event.preventDefault();
        window.confirmDialog(message, () => {
            $("#" + formId).submit()
        })
    }
</script>