routes/web.php
<?php

use App\Http\Controllers\ACLController;
use App\Http\Controllers\AgihanController;
use App\Http\Controllers\AuditLogController;
use App\Http\Controllers\CabutanController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\LampiranController;
use App\Http\Controllers\MeetingController;
use App\Http\Controllers\ReplyController;
use App\Http\Controllers\UserController;
use App\Models\Role;
use App\Services\DocumentUploadService;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('dashboard');
    // return view('welcome');
});

Auth::routes([
    'register' => false, // Registration Routes...
    // 'reset' => false, // Password Reset Routes...
    // 'verify' => false, // Email Verification Routes...
]);




Route::middleware(['auth', 'role:' . implode('|', Role::ALL_SYSTEM_ROLES)])->group(function () {
    // Route::prefix('/dokumen/{jenis}')->controller(DocumentController::class)->middleware('role:' . Role::PERANAN_PENTADBIR . '|' . Role::PERANAN_KETUA_JABATAN)->name('documents.')->group(function () {
    Route::prefix('/dokumen/{jenis}')->controller(DocumentController::class)->middleware('role:' . Role::PERANAN_PENTADBIR)->name('documents.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::post('/', 'store')->name('store');
        Route::get('/create', 'create')->name('create');
        Route::prefix('/{document}')->group(function () {
            Route::get('/', 'show')->name('show');
            Route::put('/', 'update')->name('update');
            Route::get('/edit', 'edit')->name('edit');
            Route::delete('/', 'destroy')->name('destroy');
            Route::resource('/lampirans', LampiranController::class, [
                'only'  =>  ['store', 'destroy']
            ]);
            Route::group(['prefix' => '/agihans', 'as' => 'agihans.', 'middleware'  => ['cannot-set-agihan']], function () {
                Route::post('/store', [AgihanController::class, 'store'])->name('store');
                Route::post('/resend', [AgihanController::class, 'resend'])->name('resend');
                Route::post('/reset', [AgihanController::class, 'reset'])->name('reset');
            });
        });
    });

    Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');


    Route::prefix('/mesyuarat/{jenis}')->controller(MeetingController::class)->middleware('role:' . Role::PERANAN_PENTADBIR . '|' . Role::PERANAN_KETUA_JABATAN)->name('meetings.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::post('/', 'store')->name('store');
        Route::get('/create', 'create')->name('create');
        Route::prefix('/{meeting}')->group(function () {
            Route::get('/', 'show')->name('show');
            Route::put('/', 'update')->name('update');
            Route::get('/edit', 'edit')->name('edit');
            Route::delete('/', 'destroy')->name('destroy');
            Route::get('/agihan', 'agihan')->name('agihan');
            Route::resource('/lampirans', LampiranController::class, [
                'only'  =>  ['store', 'destroy']
            ]);
            Route::resource('/cabutans', CabutanController::class, [
                'only'  =>  ['store', 'update', 'destroy']
            ]);
            Route::group(['prefix' => '/agihans', 'as' => 'agihans.'], function () {
                Route::post('/store', [AgihanController::class, 'store'])->name('store');
                Route::post('/resend', [AgihanController::class, 'resend'])->name('resend');
                Route::post('/reset', [AgihanController::class, 'reset'])->name('reset');
            });
        });
    });

    Route::controller(LampiranController::class)->prefix('lampirans')->name('lampirans.')->group(function () {
        Route::get('{lampiran}/download', 'download')->name('download');
    });

    Route::delete("/lampirans/{lampiran}", [LampiranController::class, 'destroy'])->name('lampirans.destroy');

    Route::middleware(['role:' . Role::PERANAN_PENTADBIR . '|' . Role::PERANAN_PENTADBIR_SISTEM])->group(function () {
        Route::resources([
            'departments' => DepartmentController::class,
            'users' => UserController::class,
        ]);
        Route::put('/users/{user}/changepassword', [UserController::class, 'changePassword'])->name('users.change-password');
        Route::prefix('/users/{user}/acls')->middleware('cannot-update-self-role-access')->group(function () {
            Route::put('/', [ACLController::class, 'update'])->name('acls.update');
            Route::get('/edit', [ACLController::class, 'edit'])->name('acls.edit');
            Route::post('/reset', [ACLController::class, 'reset'])->name('acls.reset');
        });
        Route::get('/acls', [ACLController::class, 'index'])->name('acls.index');
    });




    //Azrul Tambah
    Route::middleware(['role:' . Role::PERANAN_KETUA_JABATAN])->group(function () {
        Route::get('/users/{id}', [App\Http\Controllers\UserController::class, 'index'])->name('user.index');
        Route::get('/maklumbalas/index', [App\Http\Controllers\ReplyController::class, 'index'])->name('maklumbalas.index');
        Route::get('/mesyuarat/mesyuarat-jemaah-menteri', [App\Http\Controllers\MeetingController::class, 'index'])->name('mesyuarat.mesyuarat-jemaah-menteri');
        // Route::get('/mesyuarat/mesyuarat-jemaah-menteri/{meeting}', [App\Http\Controllers\MeetingController::class, 'show'])->name('mesyuarat.mesyuarat-jemaah-menteri.show');
        Route::get('/mesyuarat/mesyuarat-utama', [App\Http\Controllers\MeetingController::class, 'index'])->name('mesyuarat.mesyuarat-utama');

        Route::get('/view/docs/{lampiran}', [LampiranController::class, 'download'])->name('view.docs');
        Route::group(['prefix' => 'maklumbalas', 'as' => 'reply.'], function () {
            Route::get('/', [ReplyController::class, 'index'])->name('index')->middleware('can:view-maklum-balas');

            Route::prefix('/{model}/{model_id}/ulasan/{agihan}')->group(function () {
                Route::get('/', [ReplyController::class, 'show'])->name('show');
                Route::post('/', [ReplyController::class, 'store'])->name('store')->middleware('can-update-reply');
            })->middleware(['valid-feedback-url']);
        });

    });





    // Route::get('/dashboard', 'HomeController@index')->name('dashboard');

    Route::group(['prefix'  => '/logaudit', 'as' => 'logaudit.', 'middleware' => 'role:' . Role::PERANAN_PENTADBIR. '|' . Role::PERANAN_PENTADBIR_SISTEM], function () {
        Route::prefix('/pengguna')->name('pengguna.')->group(function () {
            Route::get('/', [AuditLogController::class, 'indexUserLogs'])->name('index');
            Route::get('/{user}/{type?}', [AuditLogController::class, 'showUserLogs'])->name('show');
        });

        Route::prefix('/dokumen')->name('dokumen.')->group(function () {
            Route::get('/{type?}', [AuditLogController::class, 'indexDocumentLogs'])->name('index');
            Route::get('/dokumen/{document}', [AuditLogController::class, 'showDocumentLogs'])->name('document.show');
            Route::get('/mesyuarat/{meeting}', [AuditLogController::class, 'showMeetingLogs'])->name('meeting.show');
        });
    });
});

Route::group(['prefix' => '/test'], function () {
    Route::get('/downloadwithwatermark/{watermarkString}', function () {

        $path = base_path("/tests/TestAssets/lorem-ipsum.pdf");

        $doc = (new DocumentUploadService())->setWatermarkToDoc($path, request()->watermarkString);

        return response()->download($doc, null);
    });
});

resources/views/layouts/elements/_sidebarpengurusan.blade.php
@if (Auth::guard('web')->id() == 1 && 2)
    <li class="nav-header text-uppercase">pengurusan
        <hr style="height:2px;border-width:0;color:gray;background-color:red">
    </li>

    <!-- Meta Data  -->
    <li class="nav-item has-treeview">
        {!! Html::buttonSidebarNavLinkTreeview('Meta Data', 'fas fa-cubes', [
            'class' => 'nav-link btn btn-block
                                            btn-link text-left',
        ]) !!}
        <ul class="nav nav-treeview">
            <li class="nav-item">
                {!! Html::buttonSidebaNavItemTree('Negara', [
                    'onclick' => "window.location='" . route('mesyuarat.mesyuarat-utama') . "'",
                    'class' =>
                        'nav-link btn btn-block btn-link text-left
                                                                                            ' .
                        Html::active('mesyuarat.mesyuarat-utama'),
                ]) !!}
            </li>
            <li class="nav-item">
                {!! Html::buttonSidebaNavItemTree('Negeri', [
                    'onclick' => "window.location='" . route('mesyuarat.mesyuarat-utama') . "'",
                    'class' =>
                        'nav-link btn btn-block btn-link text-left
                                                                                            ' .
                        Html::active('mesyuarat.mesyuarat-utama'),
                ]) !!}
            </li>
        </ul>
    </li>
@endif
@if (Auth::guard('web')->id() == 3)
<li class="nav-item has-treeview">
    {!! Html::buttonSidebarNavLinkTreeview('Data Rujukan', 'fas fa-user-shield', [
        'class' => 'nav-link btn
                                        btn-block btn-link text-left',
    ]) !!}
    <ul class="nav nav-treeview">
        @can('pengguna-list')
            <li class="nav-item">
                {!! Html::buttonSidebaNavItemTree('Pingat', [
                    'onclick' => "window.location='" . route('dashboard') . "'",
                    'class' =>
                        'nav-link btn btn-block btn-link text-left
                                                                                                            ' .
                        Html::active('dashboard'),
                ]) !!}
            </li>
        @endcan
        @can('pengguna-list')
            <li class="nav-item">
                {!! Html::buttonSidebaNavItemTree('Jabatan/Bahagian', [
                    'onclick' => "window.location='" . route('maklumbalas.index') . "'",
                    'class' =>
                        'nav-link btn btn-block btn-link text-left
                                                                                                        ' .
                        Html::active('maklumbalas.index'),
                ]) !!}
            </li>
        @endcan
    </ul>
</li>
@endif

resources/views/layouts/elements/auth.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="icon" href="{{ asset('img/jata.png') }}" type="image/icon type">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="robots" content="noindex, noimageindex, nofollow, noarchive,nocache,nosnippet,noodp,noydir">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title') | {{ config('app.name', 'Sistem e-Cores') }}</title>

    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset('plugins/fontawesome-free/css/all.min.css') }}">

    <!-- iCheck -->
    <link rel="stylesheet" href="{{ asset('plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">

    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('css/adminlte.min.css') }}">

    <!-- CSS:style
    Background
    -->

    <link rel="stylesheet" href="{{ asset('css/style.css') }}">

    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

<body class="hold-transition login-page">
<div class="display:flex; justify-content:center; text-center">
    <br><br><br><br><br><br>
    <a class="navbar-brand" href="{{ url('/') }}">
        <img src='{{ asset('img/jata.png') }}' width="180px">
    </a>
    <br>
    <h2 class="text-light font-weight-bold font-size-15">{{config('app.name')}}</h2><br />
</div>
    @yield('content')
    @yield('demo')
    <div class="container text-center">

        <span class="text-light font-weight-bold">{{config('app.agency_short')}}</span> | {{config('app.name')}}</span><br />
        <!-- Default to the left -->
        {{config('app.dept')}}<br />
        <strong>Copyright &copy; 2023 {{config('app.agency')}}</strong>

    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery -->
    <script src="{{ asset('plugins/jquery/jquery.min.js') }}"></script>
    <!-- Bootstrap 4 -->
    <script src="{{ asset('plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    @yield('page-js-script')
</body>

</html>

resources/views/layouts/elements/footer.blade.php
<footer class="main-footer  no-print">
    <div class="float-right d-none d-sm-block">
        <b>Version</b> 1.0.0
    </div>
    Copyright &copy; 2023 <span class="font-weight-bold text-logo">{{config('app.name_short')}}</span> {{config('app.dept_short')}}, {{config('app.agency_short')}} | {{config('app.name')}}</span>.

</footer>

resources/views/layouts/elements/navbar.blade.php
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
    </ul>
    <div class="container">

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav me-auto">
                @auth
                    @foreach (getNavbarMenu() as $menu)
                        @if (!isset($menu['sub_menu']))
                            @canany($menu['access'])
                                <li class="nav-item">
                                    <a class="nav-link @if (routeIsActive($menu['route'])) active @endif"
                                        href="{{ $menu['route'] }}">{{ $menu['label'] }}</a>
                                </li>
                            @endcanany
                        @else
                            @canany($menu['access'])
                                <li class="nav-item dropdown">
                                    <a class="nav-link @if (routeIsActive($menu['route'])) active @endif dropdown-toggle"
                                        href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                                        aria-expanded="false">
                                        {{ $menu['label'] }}
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        @foreach ($menu['sub_menu'] as $sub)
                                            @if ($sub && is_array($sub))
                                                @canany($sub['access'])
                                                    <li>
                                                        <a class="dropdown-item @if (routeIsActive($sub['route'])) active @endif"
                                                            href="{{ $sub['route'] }}">
                                                            {{ $sub['label'] }}
                                                        </a>
                                                    </li>
                                                @endcanany
                                            @else
                                                <li>
                                                    <hr class="dropdown-divider">
                                                </li>
                                            @endif
                                        @endforeach
                                    </ul>
                                </li>
                            @endcanany
                        @endif
                    @endforeach
                @endauth
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ms-auto">
                <!-- Authentication Links -->
                @guest
                    @if (Route::has('login'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                    @endif

                    {{-- @if (Route::has('register'))
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
            </li>
            @endif --}}
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                            data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }}
                        </a>

                        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                                onclick="event.preventDefault();
                                         document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>

resources/views/layouts/elements/navbarpublic.blade.php
<nav class="main-header navbar navbar-expand navbar-dark navbar-dark">
    <!-- Left navbar links -->
    <ul class=" wpx-80">
    </ul>
    <ul class=" wpx-80">
        <a href="/"> <img src='{{ asset('img/logokpkt.png') }}' height="40px" width="50px"></a>
    </ul>
    <ul class="wpx-40">
    </ul>
    <ul class="wpx-800">
        <span class="navbar-text font-weight-bold text-white">
            <a href="/"> <h4>Sistem eCores | {{config('app.agency_short')}}</h4></a>
        </span>
    </ul>
</nav>

resources/views/layouts/elements/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-indigo elevation-0" >
    <!-- Brand Logo -->
    {{-- <a href="{{ Auth::guard('web')->check() ? route('web.dashboard') : route('web.dashboard') }}" --}}

    {{-- <img src="{{ asset('img/jata.png') }}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
        style="opacity: .7"> --}}
    {{-- @if (Auth::guard('web')->id() == 5)
        <span class="brand-text font-weight-light">Superuser</span>
    @elseif(Auth::guard('web')->id() == 1)
        <span class="brand-text font-weight-light">Pentadbir</span>
    @endif --}}


    <!-- Sidebar -->
    <div class="sidebar">
        <br>
        <img src="{{ asset('img/jata.png') }}" alt="AdminLTE Logo" class="brand-image img-circle elevation-4"
            style="opacity: .7">
        <a class="navbar-brand" href="{{ url('/') }}">
            {{ config('app.name', 'Laravel') }}
        </a>

        <div class="user-panel mt-4 pb-4 mb-4 d-flex">
            &ensp; <div class="d-block info fa fa-user-lock" style="font-size: 11px; color:rgb(236, 213, 5)">&ensp; :
                &emsp; {{ Auth::guard('web')->user()->roles->first()->name }}
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                data-accordion="false">

                <li class="nav-item">
                    {!! Html::buttonSidebarNavLink('Dashboard', 'fas fa-tachometer-alt', [
                        'onclick' => "window.location='" . route('dashboard') . "'",
                        'class' => 'nav-link btn btn-block btn-link text-left ' . Html::active('dashboard'),
                    ]) !!}
                </li>


                {{-- @if (Auth::guard('web')->user()->roles->first()->name == 'Pentadbir') --}}
                @hasanyrole('Pentadbir')
                <li class="nav-item">
                    {!! Html::buttonSidebarNavLink('Memo-KPKT', 'fas fa-file-archive', [
                        'onclick' => "window.location='" . route('documents.index', ['jenis' => 'memo-kpkt']). "'",
                        'class' => 'nav-link btn btn-block btn-link text-left ' . Html::active('documents1.index'),
                    ]) !!}
                </li>
                <li class="nav-item">
                    {!! Html::buttonSidebarNavLink('Memo Kementerian Lain', 'fas fa-file-archive', [
                        'onclick' => "window.location='" . route('documents.index', ['jenis' => 'kementerian-lain']). "'",
                        'class' => 'nav-link btn btn-block btn-link text-left ' . Html::active('documents2.index'),
                    ]) !!}
                </li>
                <li class="nav-item">
                    {!! Html::buttonSidebarNavLink('Nota', 'fas fa-sticky-note', [
                        'onclick' => "window.location='" . route('documents.index', ['jenis' => 'nota']). "'",
                        'class' => 'nav-link btn btn-block btn-link text-left ' . Html::active('documents3.index'),
                    ]) !!}
                </li>
                @endhasanyrole
                {{-- @endif --}}
            </ul>

            @if (Auth::guard('web')->user()->roles->first()->name =='Ketua Jabatan')
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                data-accordion="false">
                <li class="nav-header text-uppercase" style="color: rgb(255, 255, 255)">Senarai Mesyuarat
                    <hr style="height:2px;border-width:0;color:gray;background-color:rgb(83, 129, 255)">
                </li>
                <li class="nav-item">
                    {!! Html::buttonSidebarNavLink('Jemaah Menteri', 'fa fa-file-alt', [
                        'onclick' => "window.location='" . route('mesyuarat.mesyuarat-jemaah-menteri') . "'",
                        'class' => 'nav-link btn btn-block btn-link text-left ' . Html::active('mesyuarat.mesyuarat-jemaah-menteri'),
                    ]) !!}
                </li>
                <li class="nav-item">
                    {!! Html::buttonSidebarNavLink('Utama', 'fa fa-file-word', [
                        'onclick' => "window.location='" . route('mesyuarat.mesyuarat-utama') . "'",
                        'class' => 'nav-link btn btn-block btn-link text-left ' . Html::active('mesyuarat.mesyuarat-utama'),
                    ]) !!}
                </li>
                <li class="nav-item">
                    {!! Html::buttonSidebarNavLink('Nota', 'fa fa-sticky-note', [
                        'onclick' => "window.location='" . route('documents.index', ['jenis' => 'nota']). "'",
                        'class' => 'nav-link btn btn-block btn-link text-left ' . Html::active('nota.index'),
                    ]) !!}
                </li>
            </ul>
            @endif

            <br>
            @if (Auth::guard('web')->user()->roles->first()->name =='Ketua Jabatan')
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                data-accordion="false">
                <li class="nav-header text-uppercase" style="color: rgb(255, 255, 255)">Tindakan
                    <hr style="height:2px;border-width:0;color:gray;background-color:gold">
                </li>

                <li class="nav-item">
                    {!! Html::buttonSidebarNavLink('Maklumbalas', 'fa fa-pen-fancy', [
                        'onclick' => "window.location='" . route('maklumbalas.index') . "'",
                        'class' => 'nav-link btn btn-block btn-link text-left ' . Html::active('maklumbalas.index'),
                    ]) !!}
                </li>
            </ul>
            @endif

            @if (Auth::guard('web')->user()->roles->first()->name == 'Pentadbir' || Auth::guard('web')->user()->roles->first()->name == 'Pentadbir Sistem' )
            <br>
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                data-accordion="false">
                <li class="nav-header text-uppercase" style="color: rgb(255, 255, 255)">Pengurusan Admin
                    <hr style="height:2px;border-width:0;color:gray;background-color:rgb(83, 129, 255)">
                </li>
                <li class="nav-item">
                    {!! Html::buttonSidebarNavLink('Pengguna Sistem', 'fa fa-user-secret', [
                        'onclick' => "window.location='" . route('users.index') . "'",
                        'class' => 'nav-link btn btn-block btn-link text-left ' . Html::active('users.index'),
                    ]) !!}
                </li>
                <li class="nav-item">
                    {!! Html::buttonSidebarNavLink('Jabatan/Kementerian', 'fa fa-building', [
                        'onclick' => "window.location='" . route('departments.index') . "'",
                        'class' => 'nav-link btn btn-block btn-link text-left ' . Html::active('departments.index'),
                    ]) !!}
                </li>
                <li class="nav-item">
                    {!! Html::buttonSidebarNavLink('Kawalan Capaian', 'fas fa-broadcast-tower', [
                        'onclick' => "window.location='" . route('acls.index') . "'",
                        'class' => 'nav-link btn btn-block btn-link text-left ' . Html::active('acls.index'),
                    ]) !!}
                </li>
                <li class="nav-header text-uppercase" style="color: rgb(255, 255, 255)">Audit Log
                    <hr style="height:2px;border-width:0;color:rgba(214, 38, 38, 0.911);background-color:rgb(180, 12, 12)">
                </li>
                <li class="nav-item">
                    {!! Html::buttonSidebarNavLink('Pengguna', 'fa fa-user-secret', [
                        'onclick' => "window.location='" . route('logaudit.pengguna.index') . "'",
                        'class' => 'nav-link btn btn-block btn-link text-left ' . Html::active('logaudit.pengguna.index'),
                    ]) !!}
                </li>
                <li class="nav-item">
                    {!! Html::buttonSidebarNavLink('Dokumen', 'fa fa-user-secret', [
                        'onclick' => "window.location='" . route('logaudit.dokumen.index') . "'",
                        'class' => 'nav-link btn btn-block btn-link text-left ' . Html::active('logaudit.dokumen.index'),
                    ]) !!}
                </li>
            </ul>
            @endif




















            <!-- /.Akses Sistem -->
            @hasanyrole('Pentadbir Sistem|Pentadbir|Pentadbir Jabatan')
            {{-- @include('layouts.elements._sidebarpengurusan') --}}
            @endhasanyrole
            <!-- /.Akses Sistem -->

            <br>
            <li class="nav-header text-uppercase" style="color: rgb(255, 255, 255)">KPKT - Meja Bantuan
                <hr style="height:2px;border-width:0;color:gray;background-color:rgb(31, 199, 241)">
            </li>
            <a href="https://edirektori.kpkt.gov.my/edirektori/index.php/home/grid/199" class="nav-link" target="_blank"
                class="brand-link navbar-purple">
                <img src="{{ asset('img/pautan.png') }}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
                    style="opacity: .7"> BSA
            </a>

            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>