routes/web.php
<?php

use App\Http\Controllers\ACLController;
use App\Http\Controllers\AgihanController;
use App\Http\Controllers\AuditLogController;
use App\Http\Controllers\CabutanController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\LampiranController;
use App\Http\Controllers\MeetingController;
use App\Http\Controllers\ReplyController;
use App\Http\Controllers\UserController;
use App\Models\Role;
use App\Services\DocumentUploadService;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('dashboard');
    // return view('welcome');
});

Auth::routes([
    'register' => false, // Registration Routes...
    // 'reset' => false, // Password Reset Routes...
    // 'verify' => false, // Email Verification Routes...
]);




Route::middleware(['auth', 'role:' . implode('|', Role::ALL_SYSTEM_ROLES)])->group(function () {
    // Route::prefix('/dokumen/{jenis}')->controller(DocumentController::class)->middleware('role:' . Role::PERANAN_PENTADBIR . '|' . Role::PERANAN_KETUA_JABATAN)->name('documents.')->group(function () {
    Route::prefix('/dokumen/{jenis}')->controller(DocumentController::class)->middleware('role:' . Role::PERANAN_PENTADBIR)->name('documents.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::post('/', 'store')->name('store');
        Route::get('/create', 'create')->name('create');
        Route::prefix('/{document}')->group(function () {
            Route::get('/', 'show')->name('show');
            Route::put('/', 'update')->name('update');
            Route::get('/edit', 'edit')->name('edit');
            Route::delete('/', 'destroy')->name('destroy');
            Route::resource('/lampirans', LampiranController::class, [
                'only'  =>  ['store', 'destroy']
            ]);
            Route::group(['prefix' => '/agihans', 'as' => 'agihans.', 'middleware'  => ['cannot-set-agihan']], function () {
                Route::post('/store', [AgihanController::class, 'store'])->name('store');
                Route::post('/resend', [AgihanController::class, 'resend'])->name('resend');
                Route::post('/reset', [AgihanController::class, 'reset'])->name('reset');
            });
        });
    });

    Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');


    Route::prefix('/mesyuarat/{jenis}')->controller(MeetingController::class)->middleware('role:' . Role::PERANAN_PENTADBIR . '|' . Role::PERANAN_KETUA_JABATAN)->name('meetings.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::post('/', 'store')->name('store');
        Route::get('/create', 'create')->name('create');
        Route::prefix('/{meeting}')->group(function () {
            Route::get('/', 'show')->name('show');
            Route::put('/', 'update')->name('update');
            Route::get('/edit', 'edit')->name('edit');
            Route::delete('/', 'destroy')->name('destroy');
            Route::get('/agihan', 'agihan')->name('agihan');
            Route::resource('/lampirans', LampiranController::class, [
                'only'  =>  ['store', 'destroy']
            ]);
            Route::resource('/cabutans', CabutanController::class, [
                'only'  =>  ['store', 'update', 'destroy']
            ]);
            Route::group(['prefix' => '/agihans', 'as' => 'agihans.'], function () {
                Route::post('/store', [AgihanController::class, 'store'])->name('store');
                Route::post('/resend', [AgihanController::class, 'resend'])->name('resend');
                Route::post('/reset', [AgihanController::class, 'reset'])->name('reset');
            });
        });
    });

    Route::controller(LampiranController::class)->prefix('lampirans')->name('lampirans.')->group(function () {
        Route::get('{lampiran}/download', 'download')->name('download');
    });

    Route::delete("/lampirans/{lampiran}", [LampiranController::class, 'destroy'])->name('lampirans.destroy');

    Route::middleware(['role:' . Role::PERANAN_PENTADBIR . '|' . Role::PERANAN_PENTADBIR_SISTEM])->group(function () {
        Route::resources([
            'departments' => DepartmentController::class,
            'users' => UserController::class,
        ]);
        Route::put('/users/{user}/changepassword', [UserController::class, 'changePassword'])->name('users.change-password');
        Route::prefix('/users/{user}/acls')->middleware('cannot-update-self-role-access')->group(function () {
            Route::put('/', [ACLController::class, 'update'])->name('acls.update');
            Route::get('/edit', [ACLController::class, 'edit'])->name('acls.edit');
            Route::post('/reset', [ACLController::class, 'reset'])->name('acls.reset');
        });
        Route::get('/acls', [ACLController::class, 'index'])->name('acls.index');
    });




    //Azrul Tambah
    Route::middleware(['role:' . Role::PERANAN_KETUA_JABATAN])->group(function () {
        Route::get('/users/{id}', [App\Http\Controllers\UserController::class, 'index'])->name('user.index');
        Route::get('/maklumbalas/index', [App\Http\Controllers\ReplyController::class, 'index'])->name('maklumbalas.index');
        Route::get('/mesyuarat/mesyuarat-jemaah-menteri', [App\Http\Controllers\MeetingController::class, 'index'])->name('mesyuarat.mesyuarat-jemaah-menteri');
        // Route::get('/mesyuarat/mesyuarat-jemaah-menteri/{meeting}', [App\Http\Controllers\MeetingController::class, 'show'])->name('mesyuarat.mesyuarat-jemaah-menteri.show');
        Route::get('/mesyuarat/mesyuarat-utama', [App\Http\Controllers\MeetingController::class, 'index'])->name('mesyuarat.mesyuarat-utama');

        Route::get('/view/docs/{lampiran}', [LampiranController::class, 'download'])->name('view.docs');
        Route::group(['prefix' => 'maklumbalas', 'as' => 'reply.'], function () {
            Route::get('/', [ReplyController::class, 'index'])->name('index')->middleware('can:view-maklum-balas');

            Route::prefix('/{model}/{model_id}/ulasan/{agihan}')->group(function () {
                Route::get('/', [ReplyController::class, 'show'])->name('show');
                Route::post('/', [ReplyController::class, 'store'])->name('store')->middleware('can-update-reply');
            })->middleware(['valid-feedback-url']);
        });

    });





    // Route::get('/dashboard', 'HomeController@index')->name('dashboard');

    Route::group(['prefix'  => '/logaudit', 'as' => 'logaudit.', 'middleware' => 'role:' . Role::PERANAN_PENTADBIR. '|' . Role::PERANAN_PENTADBIR_SISTEM], function () {
        Route::prefix('/pengguna')->name('pengguna.')->group(function () {
            Route::get('/', [AuditLogController::class, 'indexUserLogs'])->name('index');
            Route::get('/{user}/{type?}', [AuditLogController::class, 'showUserLogs'])->name('show');
        });

        Route::prefix('/dokumen')->name('dokumen.')->group(function () {
            Route::get('/{type?}', [AuditLogController::class, 'indexDocumentLogs'])->name('index');
            Route::get('/dokumen/{document}', [AuditLogController::class, 'showDocumentLogs'])->name('document.show');
            Route::get('/mesyuarat/{meeting}', [AuditLogController::class, 'showMeetingLogs'])->name('meeting.show');
        });
    });
});

Route::group(['prefix' => '/test'], function () {
    Route::get('/downloadwithwatermark/{watermarkString}', function () {

        $path = base_path("/tests/TestAssets/lorem-ipsum.pdf");

        $doc = (new DocumentUploadService())->setWatermarkToDoc($path, request()->watermarkString);

        return response()->download($doc, null);
    });
});

app/Http/Controllers/AuditLogController.php
<?php

namespace App\Http\Controllers;

use App\Models\AuditLog;
use App\Models\Document;
use App\Models\Meeting;
use App\Models\User;

class AuditLogController extends Controller
{
    private function getUserService()
    {
        return app('UserService')->setCurrentUser(auth()->user());
    }

    public function indexUserLogs()
    {
        $validated = request()->validate([
            'page'      => 'bail|integer',
            'carian'    => 'bail|string|nullable'
        ]);

        $users = $this->getUserService()->getUsers($validated);

        return view('AuditLog.users.index', [
            'users' => $users
        ]);
    }

    public function showUserLogs(User $user, $type = '')
    {
        request()->validate([
            'type'      => 'bail|string|in:aktiviti,akaun|nullable',
        ]);

        if (!$type) {
            return redirect()->route('logaudit.pengguna.show', [$user, 'aktiviti']);
        }

        $accountLogs = $user->auditLogs()
            ->where('changes->logged_in_at', null)
            ->where('changes->logged_out_at', null)
            ->orderBy('created_at', 'DESC')
            ->orderBy('id', 'DESC')
            ->paginate(20, ['*'], 'user_account_log_page', request('user_account_log_page', 1));

        $activityLogs = AuditLog::where('performed_by', $user->id)
            ->orderBy('created_at', 'DESC')
            ->orderBy('id', 'DESC')
            ->paginate(20, ['*'], 'user_activity_log_page', request('user_activity_log_page', 1));

        return view('AuditLog.users.show', [
            'account_logs'  => $accountLogs,
            'activity_logs' => $activityLogs
        ]);
    }

    public function indexDocumentLogs($type = '')
    {
        request()->validate([
            'type'      => 'bail|string|in:aktiviti,akaun|nullable',
        ]);

        if (!$type) {
            return redirect()->route('logaudit.dokumen.index', ['dokumen']);
        }

        $documents = Document::when(request()->carian, function ($q) {
            $q->where(function ($sub) {
                $sub->where('name', 'LIKE', '%' . request()->carian . '%')
                    ->orWhere('sub_name', 'LIKE', '%' . request()->carian . '%')
                    ->orWhere('no_fail_kementerian', 'LIKE', '%' . request()->carian . '%');
            });
        })->orderBy('id', 'DESC')->orderBy('created_at', 'DESC')
            ->paginate(20, ['*'], 'documents_page', request('documents_page', 1));

        $meetings = Meeting::when(request()->carian, function ($q) {
            $q->where(function ($sub) {
                $sub->where('name', 'LIKE', '%' . request()->carian . '%');
            });
        })->orderBy('id', 'DESC')->orderBy('created_at', 'DESC')
            ->paginate(20, ['*'], 'meetings_page', request('meetings_page', 1));

        return view('AuditLog.documents.index', [
            'documents' => $documents,
            'meetings'  => $meetings
        ]);
    }

    public function showDocumentLogs(Document $document)
    {
        return view('AuditLog.documents.documents', [
            'logs'  => $document->auditLogs()->orderBy('created_at', 'DESC')
                ->orderBy('id', 'DESC')
                ->paginate(20)
        ]);
    }

    public function showMeetingLogs(Meeting $meeting)
    {
        return view('AuditLog.documents.meetings', [
            'logs'  => $meeting->auditLogs()->orderBy('created_at', 'DESC')
                ->orderBy('id', 'DESC')
                ->paginate(20)
        ]);
    }
}

app/Http/Controllers/DocumentController.php
<?php

namespace App\Http\Controllers;

use App\Action\CreateLampiran;
use App\Http\Requests\StoreDocumentRequest;
use App\Http\Requests\UpdateDocumentRequest;
use App\Models\Department;
use App\Models\Document;
use App\Models\Ministry;
use Illuminate\Http\Request;

class DocumentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $documents = Document::where('jenis', $request->jenis)
            ->when(request()->carian, function ($q) {
                $q->where(function ($sub) {
                    $sub->where('name', 'LIKE', '%' . request()->carian . '%')
                        ->orWhere('sub_name', 'LIKE', '%' . request()->carian . '%')
                        ->orWhere('no_fail_kementerian', 'LIKE', '%' . request()->carian . '%');
                });
            })
            ->orderBy('name', 'ASC')
            ->paginate(10);

        return view('Document.index', [
            'jenis' => $request->jenis,
            'documents' => $documents,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        return view('Document.create-multistep', [
            'jenis' => $request->jenis,
            'departments' => Department::all(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreDocumentRequest  $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store($jenis, StoreDocumentRequest $request)
    {
        $validated = $request->validated();

        Document::create(array_merge($validated, [
            'created_by'    => auth()->user()->id
        ]));

        session()->flash('status', [
            'type' => 'success',
            'message' => 'Maklumat berjaya disimpan.',
        ]);

        return redirect(route('documents.index', [
            'jenis' => request()->jenis,
        ]));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Document  $document
     *
     * @return \Illuminate\Http\Response
     */
    public function show(Document $document)
    {
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Document  $document
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($jenis, Document $document)
    {
        if (!isset(request()->step) || (!in_array(request()->step, [1, 2, 3]))) {
            return redirect()->route('documents.edit', ['jenis' => request()->jenis, 'document' => $document->id, 'step' => 1]);
        }

        $lampirans = $document->lampirans()->orderBy('name', 'ASC')->paginate(10, ['*'], 'lampiran_page');

        return view('Document.edit-multistep', [
            'jenis'                     => $document->jenis,
            'document'                  => $document,
            'departments'               => Department::orderBy('name', 'asc')->get(),
            'lampirans'                 => $lampirans
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateDocumentRequest  $request
     * @param  \App\Models\Document  $document
     *
     * @return \Illuminate\Http\Response
     */
    public function update($jenis, Document $document, UpdateDocumentRequest $request)
    {
        $validated = $request->validated();

        $document->update($validated);

        $request->session()->flash('status', [
            'type' => 'success',
            'message' => 'Maklumat berjaya dikemaskini.',
        ]);

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Document  $document
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($jenis, Document $document)
    {
        $document->delete();

        if ($document) {
            request()->session()->flash('status', [
                'type' => 'success',
                'message' => 'Maklumat Berjaya Dihapus',
            ]);
        } else {
            request()->session()->flash('status', [
                'type' => 'danger',
                'message' => 'Maklumat Gagal Dihapus',
            ]);
        }

        return redirect(route('documents.index', ['jenis' => request()->jenis]));
    }

    private function validateUploadFile(Request $request)
    {

        if ($request->has('fail_lampiran_mesyuarat')) {
            foreach ($request->file('fail_lampiran_mesyuarat') as $file) {
                validator(['fail_lampiran_mesyuarat' => $file], [
                    'fail_lampiran_mesyuarat' => 'mimes:pdf'
                ])->validate();
            }
        }

        if ($request->has('fail_lampiran_lain')) {
            foreach ($request->file('fail_lampiran_lain') as $file) {
                validator(['fail_lampiran_lain' => $file], [
                    'fail_lampiran_lain' => 'mimes:pdf'
                ])->validate();
            }
        }

        if ($request->has('fail_lampiran_ringkasan')) {
            foreach ($request->file('fail_lampiran_ringkasan') as $file) {
                validator(['fail_lampiran_ringkasan' => $file], [
                    'fail_lampiran_ringkasan' => 'mimes:pdf'
                ])->validate();
            }
        }

        if ($request->has('fail_lampiran_tambahan')) {
            foreach ($request->file('fail_lampiran_tambahan') as $file) {
                validator(['fail_lampiran_tambahan' => $file], [
                    'fail_lampiran_tambahan' => 'mimes:pdf'
                ])->validate();
            }
        }
    }
}

resources/views/AuditLog/documents/documents.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Log Audit <strong>{{ request()->route('document')->name }}</strong> ({{ parseDocumentType(request()->route('document')->jenis) }})
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th width="15%" class="text-center">Tarikh/Masa</th>
                                    <th width="85%">Log</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($logs as $log)
                                <tr>
                                    <td class="text-center"> {{ date('d/m/Y h:i a', strtotime($log->created_at)) }}</td>
                                    <td>{!! parseDocumentLog($log) !!}</td>
                                </tr>
                                @empty
                                <tr>
                                    <td class="text-center" colspan="2">Tiada log.</td>
                                </tr>
                                @endforelse
                            </tbody>
                        </table>
                        {{ $logs->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/AuditLog/documents/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Log Audit Dokumen
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12 d-flex justify-content-between">
                            <ul class="nav nav-pills" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link @if(request()->route('type') === 'dokumen') active disabled @endif" href="{{ route('logaudit.dokumen.index', ['dokumen']) }}" role="tab">Dokumen</a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link @if(request()->route('type') === 'mesyuarat') active disabled @endif" href="{{ route('logaudit.dokumen.index', ['mesyuarat']) }}" role="tab">Mesyuarat</a>
                                </li>
                            </ul>
                        </div>

                        <div class="col-md-12 mt-2">
                            <div class="tab-content">
                                <div class="tab-pane @if(request()->route('type') === 'dokumen') active @endif" role="tabpanel">
                                    <div class="card">
                                        <div class="card-body">
                                            <div class="d-flex">
                                                <x-carian reset-route="{{ route('logaudit.dokumen.index', ['dokumen']) }}"></x-carian>
                                            </div>
                                            <div class="table-responsive">
                                                <table class="table text-center">
                                                    <thead>
                                                        <tr>
                                                            <th>Bil</th>
                                                            <th>Tarikh Dokumen</th>
                                                            <th>No. Fail</th>
                                                            <th>Tajuk / Sub Tajuk Dokumen</th>
                                                            <th>Tarikh Kemaskini</th>
                                                            <th></th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        @forelse ($documents as $document)
                                                        <tr>
                                                            <td>{{ $loop->iteration + $documents->firstItem() - 1 }}</td>
                                                            <td>{{ $document->tarikh_dokumen }}</td>
                                                            <td>{{ $document->no_fail_kementerian }}</td>
                                                            <td>{{ $document->name }} / {{ $document->sub_name }}</td>
                                                            <td>{{ $document->updated_at }}</td>
                                                            <td>
                                                                <a href="{{ route('logaudit.dokumen.document.show', [$document->id]) }}" class="btn btn-primary btn-sm">Lihat</a>
                                                            </td>
                                                        </tr>
                                                        @empty
                                                        <tr>
                                                            <td colspan="6">Tiada dokumen.</td>
                                                        </tr>
                                                        @endforelse
                                                    </tbody>
                                                </table>
                                                {{ $documents->withQueryString()->links() }}
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="tab-pane @if(request()->route('type') === 'mesyuarat') active @endif" role="tabpanel">
                                    <div class="card">
                                        <div class="card-body">
                                            <div class="d-flex">
                                                <x-carian reset-route="{{ route('logaudit.dokumen.index', ['mesyuarat']) }}"></x-carian>
                                            </div>
                                            <div class="table-responsive">
                                                <table class="table text-center">
                                                    <thead>
                                                        <tr>
                                                            <th>Bil</th>
                                                            <th>Tarikh Minit</th>
                                                            <th>Tujuan</th>
                                                            <th>No Fail / Tajuk Minit</th>
                                                            <th>Tarikh Akhir Maklum Balas</th>
                                                            <th></th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        @forelse ($meetings as $meeting)
                                                        <tr>
                                                            <td>{{ $loop->iteration + $meetings->firstItem() - 1 }}</td>
                                                            <td>{{ $meeting->tarikh_mesyuarat }}</td>
                                                            <td>{{ $meeting->tujuan }}</td>
                                                            <td>{{ $meeting->no_rujukan_fail }} / {{ $meeting->name }}</td>
                                                            <td>{{ $meeting->tarikh_tutup != null ? $meeting->tarikh_tutup : 'Belum Ditetapkan' }}
                                                            </td>
                                                            <td>
                                                                <a href="{{ route('logaudit.dokumen.meeting.show', [$meeting->id]) }}" class="btn btn-primary btn-sm">Lihat</a>
                                                            </td>
                                                        </tr>
                                                        @empty
                                                        <tr>
                                                            <td colspan="6">Tiada dokumen.</td>
                                                        </tr>
                                                        @endforelse
                                                    </tbody>
                                                </table>
                                                {{ $meetings->withQueryString()->links() }}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/AuditLog/documents/meetings.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Log Audit <strong>{{ request()->route('meeting')->name }}</strong> ({{ parseDocumentType(request()->route('meeting')->jenis) }})
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th width="15%" class="text-center">Tarikh/Masa</th>
                                    <th width="85%">Log</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($logs as $log)
                                <tr>
                                    <td class="text-center"> {{ date('d/m/Y h:i a', strtotime($log->created_at)) }}</td>
                                    <td>{!! parseMeetingLog($log) !!}</td>
                                </tr>
                                @empty
                                <tr>
                                    <td class="text-center" colspan="2">Tiada log.</td>
                                </tr>
                                @endforelse
                            </tbody>
                        </table>
                        {{ $logs->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection