routes/web.php
<?php

use App\Http\Controllers\ACLController;
use App\Http\Controllers\AgihanController;
use App\Http\Controllers\AuditLogController;
use App\Http\Controllers\CabutanController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\LampiranController;
use App\Http\Controllers\MeetingController;
use App\Http\Controllers\ReplyController;
use App\Http\Controllers\UserController;
use App\Models\Role;
use App\Services\DocumentUploadService;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('dashboard');
    // return view('welcome');
});

Auth::routes([
    'register' => false, // Registration Routes...
    // 'reset' => false, // Password Reset Routes...
    // 'verify' => false, // Email Verification Routes...
]);




Route::middleware(['auth', 'role:' . implode('|', Role::ALL_SYSTEM_ROLES)])->group(function () {
    // Route::prefix('/dokumen/{jenis}')->controller(DocumentController::class)->middleware('role:' . Role::PERANAN_PENTADBIR . '|' . Role::PERANAN_KETUA_JABATAN)->name('documents.')->group(function () {
    Route::prefix('/dokumen/{jenis}')->controller(DocumentController::class)->middleware('role:' . Role::PERANAN_PENTADBIR)->name('documents.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::post('/', 'store')->name('store');
        Route::get('/create', 'create')->name('create');
        Route::prefix('/{document}')->group(function () {
            Route::get('/', 'show')->name('show');
            Route::put('/', 'update')->name('update');
            Route::get('/edit', 'edit')->name('edit');
            Route::delete('/', 'destroy')->name('destroy');
            Route::resource('/lampirans', LampiranController::class, [
                'only'  =>  ['store', 'destroy']
            ]);
            Route::group(['prefix' => '/agihans', 'as' => 'agihans.', 'middleware'  => ['cannot-set-agihan']], function () {
                Route::post('/store', [AgihanController::class, 'store'])->name('store');
                Route::post('/resend', [AgihanController::class, 'resend'])->name('resend');
                Route::post('/reset', [AgihanController::class, 'reset'])->name('reset');
            });
        });
    });

    Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');


    Route::prefix('/mesyuarat/{jenis}')->controller(MeetingController::class)->middleware('role:' . Role::PERANAN_PENTADBIR . '|' . Role::PERANAN_KETUA_JABATAN)->name('meetings.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::post('/', 'store')->name('store');
        Route::get('/create', 'create')->name('create');
        Route::prefix('/{meeting}')->group(function () {
            Route::get('/', 'show')->name('show');
            Route::put('/', 'update')->name('update');
            Route::get('/edit', 'edit')->name('edit');
            Route::delete('/', 'destroy')->name('destroy');
            Route::get('/agihan', 'agihan')->name('agihan');
            Route::resource('/lampirans', LampiranController::class, [
                'only'  =>  ['store', 'destroy']
            ]);
            Route::resource('/cabutans', CabutanController::class, [
                'only'  =>  ['store', 'update', 'destroy']
            ]);
            Route::group(['prefix' => '/agihans', 'as' => 'agihans.'], function () {
                Route::post('/store', [AgihanController::class, 'store'])->name('store');
                Route::post('/resend', [AgihanController::class, 'resend'])->name('resend');
                Route::post('/reset', [AgihanController::class, 'reset'])->name('reset');
            });
        });
    });

    Route::controller(LampiranController::class)->prefix('lampirans')->name('lampirans.')->group(function () {
        Route::get('{lampiran}/download', 'download')->name('download');
    });

    Route::delete("/lampirans/{lampiran}", [LampiranController::class, 'destroy'])->name('lampirans.destroy');

    Route::middleware(['role:' . Role::PERANAN_PENTADBIR . '|' . Role::PERANAN_PENTADBIR_SISTEM])->group(function () {
        Route::resources([
            'departments' => DepartmentController::class,
            'users' => UserController::class,
        ]);
        Route::put('/users/{user}/changepassword', [UserController::class, 'changePassword'])->name('users.change-password');
        Route::prefix('/users/{user}/acls')->middleware('cannot-update-self-role-access')->group(function () {
            Route::put('/', [ACLController::class, 'update'])->name('acls.update');
            Route::get('/edit', [ACLController::class, 'edit'])->name('acls.edit');
            Route::post('/reset', [ACLController::class, 'reset'])->name('acls.reset');
        });
        Route::get('/acls', [ACLController::class, 'index'])->name('acls.index');
    });




    //Azrul Tambah
    Route::middleware(['role:' . Role::PERANAN_KETUA_JABATAN])->group(function () {
        Route::get('/users/{id}', [App\Http\Controllers\UserController::class, 'index'])->name('user.index');
        Route::get('/maklumbalas/index', [App\Http\Controllers\ReplyController::class, 'index'])->name('maklumbalas.index');
        Route::get('/mesyuarat/mesyuarat-jemaah-menteri', [App\Http\Controllers\MeetingController::class, 'index'])->name('mesyuarat.mesyuarat-jemaah-menteri');
        // Route::get('/mesyuarat/mesyuarat-jemaah-menteri/{meeting}', [App\Http\Controllers\MeetingController::class, 'show'])->name('mesyuarat.mesyuarat-jemaah-menteri.show');
        Route::get('/mesyuarat/mesyuarat-utama', [App\Http\Controllers\MeetingController::class, 'index'])->name('mesyuarat.mesyuarat-utama');

        Route::get('/view/docs/{lampiran}', [LampiranController::class, 'download'])->name('view.docs');
        Route::group(['prefix' => 'maklumbalas', 'as' => 'reply.'], function () {
            Route::get('/', [ReplyController::class, 'index'])->name('index')->middleware('can:view-maklum-balas');

            Route::prefix('/{model}/{model_id}/ulasan/{agihan}')->group(function () {
                Route::get('/', [ReplyController::class, 'show'])->name('show');
                Route::post('/', [ReplyController::class, 'store'])->name('store')->middleware('can-update-reply');
            })->middleware(['valid-feedback-url']);
        });

    });





    // Route::get('/dashboard', 'HomeController@index')->name('dashboard');

    Route::group(['prefix'  => '/logaudit', 'as' => 'logaudit.', 'middleware' => 'role:' . Role::PERANAN_PENTADBIR. '|' . Role::PERANAN_PENTADBIR_SISTEM], function () {
        Route::prefix('/pengguna')->name('pengguna.')->group(function () {
            Route::get('/', [AuditLogController::class, 'indexUserLogs'])->name('index');
            Route::get('/{user}/{type?}', [AuditLogController::class, 'showUserLogs'])->name('show');
        });

        Route::prefix('/dokumen')->name('dokumen.')->group(function () {
            Route::get('/{type?}', [AuditLogController::class, 'indexDocumentLogs'])->name('index');
            Route::get('/dokumen/{document}', [AuditLogController::class, 'showDocumentLogs'])->name('document.show');
            Route::get('/mesyuarat/{meeting}', [AuditLogController::class, 'showMeetingLogs'])->name('meeting.show');
        });
    });
});

Route::group(['prefix' => '/test'], function () {
    Route::get('/downloadwithwatermark/{watermarkString}', function () {

        $path = base_path("/tests/TestAssets/lorem-ipsum.pdf");

        $doc = (new DocumentUploadService())->setWatermarkToDoc($path, request()->watermarkString);

        return response()->download($doc, null);
    });
});

app/Models/Department.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'code',
        'shortcode',
        'section',
    ];

    // ---------------------------------
    // Relationship
    // ---------------------------------
    public function users()
    {
        return $this->hasMany(User::class);
    }
}

app/Http/Controllers/DepartmentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Department;
use Illuminate\Http\Request;

class DepartmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('Department.index', [
            'departments' => Department::all(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Department.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required|string',
            'code' => 'required|string',
            'shortcode' => 'required|alpha_dash|unique:departments,shortcode',
            'section' => 'required|string',
        ]);

        $department = new Department();
        $department->name = $validated['name'];
        $department->code = $validated['code'];
        $department->shortcode = $validated['shortcode'];
        $department->section = $validated['section'];
        $department->save();

        if ($department) {
            $request->session()->flash('status', [
                'type' => 'success',
                'message' => 'Maklumat Berjaya Disimpan',
            ]);
        } else {
            $request->session()->flash('status', [
                'type' => 'danger',
                'message' => 'Maklumat Gagal Disimpan',
            ]);
        }

        return redirect(route('departments.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Department  $department
     *
     * @return \Illuminate\Http\Response
     */
    public function show(Department $department)
    {
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Department  $department
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(Department $department)
    {
        return view('Department.edit', [
            'department' => $department,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Department  $department
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Department $department)
    {
        $validated = $request->validate([
            'name' => 'required|string',
            'code' => 'required|string',
            'shortcode' => 'required|alpha_dash|unique:departments,shortcode,' . $department->id,
            'section' => 'required|string',
        ]);

        $department->name = $validated['name'];
        $department->code = $validated['code'];
        $department->shortcode = $validated['shortcode'];
        $department->section = $validated['section'];
        $department->save();

        if ($department) {
            $request->session()->flash('status', [
                'type' => 'success',
                'message' => 'Maklumat Berjaya Dikemaskini',
            ]);
        } else {
            $request->session()->flash('status', [
                'type' => 'danger',
                'message' => 'Maklumat Gagal Dikemaskini',
            ]);
        }

        return redirect(route('departments.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Department  $department
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy(Department $department)
    {
        $department->delete();

        if ($department) {
            request()->session()->flash('status', [
                'type' => 'success',
                'message' => 'Maklumat Berjaya Dihapus',
            ]);
        } else {
            request()->session()->flash('status', [
                'type' => 'danger',
                'message' => 'Maklumat Gagal Dihapus',
            ]);
        }

        return redirect(route('departments.index'));
    }
}

resources/views/Department/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header d-flex justify-content-between">
                        <div class="my-auto">Jabatan/Kementerian</div>
                        <a class="btn btn-outline-primary" href="{{ route('departments.index') }}">Back</a>
                    </div>

                    <div class="card-body">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif


                        <form action="{{ route('departments.store') }}" method="POST">
                            @csrf

                            <div class="form-group mb-3">
                                <label for="Shortcode">Bahagian</label>
                                <input type="text" name="section" placeholder="Contoh : Bahagian Kewangan"
                                    class="form-control @error('section') is-invalid @enderror">
                                @error('section')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>


                            <div class="form-group mb-3">
                                <label for="Name">Nama Jabatan / Kementerian</label>
                                <input type="text" name="name"
                                    placeholder="Contoh : Jabatan Kerajaan Tempatan , Kementerian Perumahan dan Kerajaan Tempatan"
                                    class="form-control @error('name') is-invalid @enderror">
                                @error('name')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group mb-3">
                                <label for="Code">Code</label>
                                <input type="text" name="code" placeholder="Contoh : K01"
                                    class="form-control @error('code') is-invalid @enderror">
                                @error('code')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group mb-3">
                                <label for="Shortcode">Shortcode</label>
                                <input type="text" name="shortcode" placeholder="Contoh : BKewJKT"
                                    class="form-control @error('shortcode') is-invalid @enderror">
                                @error('shortcode')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>



                            <button class="float-end btn btn-primary" type="submit">Save</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/Department/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header d-flex justify-content-between">
                        <div class="my-auto">
                            Edit Jabatan <strong>{{ $department->name }}</strong>
                        </div>
                        <a class="btn btn-outline-primary" href="{{ route('departments.index') }}">Back</a>
                    </div>

                    <div class="card-body">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif


                        <form action="{{ route('departments.update', $department) }}" method="POST">
                            @csrf
                            @method('PUT')

                            <div class="form-group mb-3">
                                <label for="Shortcode">Bahagian</label>
                                <input type="text" name="section"
                                    value={{ $department->section }}placeholder="Contoh : Bahagian Kewangan"
                                    class="form-control @error('section') is-invalid @enderror">
                                @error('section')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-group mb-3">
                                <label for="Name">Nama Jabatan / Kementerian</label>
                                <input type="text" name="name" Contoh : Jabatan Kerajaan Tempatan , Kementerian
                                    Perumahan dan Kerajaan Tempatan class="form-control @error('name') is-invalid @enderror"
                                    value="{{ $department->name }}">
                                @error('name')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group mb-3">
                                <label for="Code">Code</label>
                                <input type="text" name="code" placeholder="Contoh : K01"
                                    class="form-control @error('code') is-invalid @enderror"
                                    value="{{ $department->code }}">
                                @error('code')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group mb-3">
                                <label for="Shortcode">Shortcode</label>
                                <input type="text" name="shortcode" placeholder="Contoh : BKewJKT"
                                    class="form-control @error('shortcode') is-invalid @enderror"
                                    value="{{ $department->shortcode }}">
                                @error('shortcode')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>

                            <button class="float-end btn btn-primary" type="submit">Kemaskini</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/Department/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">

                    <div class="card-footer my-auto clearfix"> Department
                        <a class="btn btn-primary float-right"
                        href="{{ route('departments.create') }}">Cipta
                        baharu</a>
                    </div>


                    <div class="card-body table-responsive">

                        @if (session('status'))
                            <div class="alert alert-{{ session('status.type') }}" role="alert">
                                {{ session('status.message') }}
                            </div>
                        @endif

                        <table class="table text-center">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Name</th>
                                    <th>Code</th>
                                    <th>Shortcode</th>
                                    <th>Bahagian</th>
                                    <th>Tindakan</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($departments as $department)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td class="float-left">{{ $department->name }}</td>
                                        <td>{{ $department->code }}</td>
                                        <td>{{ $department->shortcode }}</td>
                                        <td>{{ $department->section }}</td>
                                        <td><a href="{{ route('departments.edit', $department) }}"
                                                class="btn btn-warning">Edit</a>
                                            <!-- Button trigger modal -->
                                            <button type="button" class="btn btn-danger" data-bs-toggle="modal"
                                                data-bs-target="#deleteModal">
                                                Hapus
                                            </button>

                                            <!-- Modal -->
                                            <div class="modal fade" id="deleteModal" tabindex="-1"
                                                aria-labelledby="deleteModalLabel" aria-hidden="true">
                                                <div class="modal-dialog">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h1 class="modal-title fs-5" id="deleteModalLabel">Hapus
                                                                {{ $department->name }}
                                                            </h1>
                                                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                                aria-label="Close"></button>
                                                        </div>
                                                        <div class="modal-body">
                                                            Anda pasti ingin menghapus Jabatan {{ $department->name }}?
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-secondary"
                                                                data-bs-dismiss="modal">Batal</button>
                                                            <form action="{{ route('departments.destroy', $department) }}"
                                                                method="post">
                                                                @csrf
                                                                @method('delete')
                                                                <button type="submit"
                                                                    class="btn btn-primary">Hapus</button>
                                                            </form>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="5">No data</td>
                                    </tr>
                                @endforelse

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection